/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MyPollsRouteImport } from './routes/my-polls'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PollPollIdRouteImport } from './routes/poll.$pollId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPollsRoute = MyPollsRouteImport.update({
  id: '/my-polls',
  path: '/my-polls',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PollPollIdRoute = PollPollIdRouteImport.update({
  id: '/poll/$pollId',
  path: '/poll/$pollId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/my-polls': typeof MyPollsRoute
  '/profile': typeof ProfileRoute
  '/poll/$pollId': typeof PollPollIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/my-polls': typeof MyPollsRoute
  '/profile': typeof ProfileRoute
  '/poll/$pollId': typeof PollPollIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/my-polls': typeof MyPollsRoute
  '/profile': typeof ProfileRoute
  '/poll/$pollId': typeof PollPollIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/explore'
    | '/home'
    | '/my-polls'
    | '/profile'
    | '/poll/$pollId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/explore'
    | '/home'
    | '/my-polls'
    | '/profile'
    | '/poll/$pollId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/explore'
    | '/home'
    | '/my-polls'
    | '/profile'
    | '/poll/$pollId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  HomeRoute: typeof HomeRoute
  MyPollsRoute: typeof MyPollsRoute
  ProfileRoute: typeof ProfileRoute
  PollPollIdRoute: typeof PollPollIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-polls': {
      id: '/my-polls'
      path: '/my-polls'
      fullPath: '/my-polls'
      preLoaderRoute: typeof MyPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$pollId': {
      id: '/poll/$pollId'
      path: '/poll/$pollId'
      fullPath: '/poll/$pollId'
      preLoaderRoute: typeof PollPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  HomeRoute: HomeRoute,
  MyPollsRoute: MyPollsRoute,
  ProfileRoute: ProfileRoute,
  PollPollIdRoute: PollPollIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
